/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: d2807a225bc67c7cfdc34ef752a896cb)
interface __BaseEnv_Env {
  OAUTH_KV: KVNamespace;
  PUBLIC_ORIGIN: "https://lorimar-weddings-mcp.patrick-07a.workers.dev";
  TRIPLESEAT_SITE_ID: "6368";
  CONNECTIONS: DurableObjectNamespace<
    import("./src/server").TripleseatConnection
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "TripleseatConnection";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "PUBLIC_ORIGIN" | "TRIPLESEAT_SITE_ID">
  > {}
}
